project_id = "olbedjfebvbojlahhvpq"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.check-stripe-connection]
    verify_jwt = false
  [functions.check-subscription]
    verify_jwt = false
  [functions.create-checkout]
    verify_jwt = false
  [functions.create-setup-link]
    verify_jwt = false
  [functions.create-subscription]
    verify_jwt = false
  [functions.customer-portal]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.public-client-portal]
    verify_jwt = false
  [functions.public-operator-intake]
    verify_jwt = false
  [functions.renter-portal]
    verify_jwt = false
  [functions.renter-portal-access-admin]
    verify_jwt = false
  [functions.renter-portal-admin]
    verify_jwt = false
  [functions.save-stripe-key]
    verify_jwt = false
  [functions.send-billing-reminders]
    verify_jwt = false
  [functions.stripe-webhook]
    verify_jwt = false
