import { ImportField } from "./types";

export const RENTER_FIELDS: ImportField[] = [
  {
    key: "name",
    label: "Name",
    placeholder: "",
    synonyms: ["full name", "renter name", "customer name", "renter full name", "tenant name", "customer", "client", "client name"],
    group: "renter",
  },
  {
    key: "phone",
    label: "Phone",
    placeholder: "",
    synonyms: ["phone number", "mobile", "cell", "cell phone", "telephone", "tel", "ph", "contact"],
    group: "renter",
  },
  {
    key: "email",
    label: "Email",
    placeholder: "",
    synonyms: ["email address", "e-mail", "email addr"],
    group: "renter",
  },
  {
    key: "address",
    label: "Address",
    placeholder: "",
    synonyms: ["service address", "home address", "street address", "location", "addr", "delivery address", "install address"],
    group: "renter",
  },
  {
    key: "dryer_outlet",
    label: "Dryer Outlet",
    placeholder: "",
    synonyms: ["outlet", "outlet type", "dryer prong", "prong type"],
    group: "renter",
  },
  {
    key: "secondary_contact",
    label: "Secondary Contact",
    placeholder: "",
    synonyms: ["alt contact", "alternate contact", "second contact", "emergency contact"],
    group: "renter",
  },
  {
    key: "language",
    label: "Language",
    placeholder: "",
    synonyms: ["preferred language", "lang"],
    group: "renter",
  },
  {
    key: "status",
    label: "Status",
    placeholder: "",
    synonyms: ["renter status", "customer status", "account status"],
    group: "renter",
  },
  {
    key: "lease_start_date",
    label: "Lease Start Date",
    placeholder: "",
    synonyms: ["start date", "lease begins", "lease date", "move in date", "install date"],
    group: "renter",
  },
  {
    key: "monthly_rate",
    label: "Monthly Rate",
    placeholder: "",
    synonyms: ["monthly rent", "rent", "rate", "monthly rate $", "monthly fee", "monthly", "mo rate", "rent/mo", "rent mo"],
    group: "renter",
  },
  {
    key: "late_fee",
    label: "Late Fee",
    placeholder: "",
    synonyms: ["late fee $", "late charge", "penalty"],
    group: "renter",
  },
  {
    key: "install_fee",
    label: "Install Fee",
    placeholder: "",
    synonyms: ["install fee $", "installation fee", "setup fee"],
    group: "renter",
  },
  {
    key: "deposit_amount",
    label: "Deposit",
    placeholder: "",
    synonyms: ["deposit $", "security deposit", "deposit amount"],
    group: "renter",
  },
  {
    key: "install_fee_collected",
    label: "Install Fee Collected",
    placeholder: "",
    synonyms: ["install fee paid", "install collected"],
    group: "renter",
  },
  {
    key: "deposit_collected",
    label: "Deposit Collected",
    placeholder: "",
    synonyms: ["deposit paid", "deposit received"],
    group: "renter",
  },
  {
    key: "install_notes",
    label: "Install Notes",
    placeholder: "",
    synonyms: ["installation notes", "install info"],
    group: "renter",
  },
  {
    key: "notes",
    label: "Notes",
    placeholder: "",
    synonyms: ["renter notes", "customer notes", "comments"],
    group: "renter",
  },
  {
    key: "has_payment_method",
    label: "Card Set Up but no Autopay",
    placeholder: "",
    synonyms: [
      "card on file no autopay",
      "card added no autopay",
      "card set up no autopay",
      "payment method",
      "card on file",
    ],
    group: "renter",
  },
];

export const MACHINE_FIELDS: ImportField[] = [
  {
    key: "type",
    label: "Type",
    placeholder: "",
    synonyms: ["machine type", "appliance type", "washer or dryer", "equipment type", "make", "appliance", "w/d", "washer dryer"],
    group: "machine",
  },
  {
    key: "model",
    label: "Model",
    placeholder: "",
    synonyms: ["model number", "model name", "model #", "model no", "model num"],
    group: "machine",
  },
  {
    key: "serial",
    label: "Serial #",
    placeholder: "",
    synonyms: ["serial number", "serial #", "sn", "serial no", "serial num", "s/n", "ser", "serial#"],
    group: "machine",
  },
  {
    key: "prong",
    label: "Prong",
    placeholder: "",
    synonyms: ["prong type", "cord type", "plug type"],
    group: "machine",
  },
  {
    key: "condition",
    label: "Condition",
    placeholder: "",
    synonyms: ["machine condition", "state", "cond"],
    group: "machine",
  },
  {
    key: "status",
    label: "Status",
    placeholder: "",
    synonyms: ["machine status", "availability", "avail", "in use"],
    group: "machine",
  },
  {
    key: "cost_basis",
    label: "Cost Basis ($)",
    placeholder: "",
    synonyms: ["cost", "cost basis $", "purchase price", "price", "acquisition cost"],
    group: "machine",
  },
  {
    key: "sourced_from",
    label: "Sourced From",
    placeholder: "",
    synonyms: ["source", "acquired from", "vendor", "supplier", "purchased from"],
    group: "machine",
  },
  {
    key: "notes",
    label: "Notes",
    placeholder: "",
    synonyms: ["machine notes", "comments"],
    group: "machine",
  },
];
