import { ImportField } from "./types";

const RENTER_STATUS_MAP: Record<string, string> = {
  active: "active",
  lead: "lead",
  scheduled: "scheduled",
  late: "late",
  maintenance: "maintenance",
  termination_requested: "termination_requested",
  "termination requested": "termination_requested",
  pickup_scheduled: "pickup_scheduled",
  "pickup scheduled": "pickup_scheduled",
  closed: "closed",
  defaulted: "defaulted",
  archived: "archived",
  "former customer": "archived",
  former: "archived",
  inactive: "archived",
  cancelled: "closed",
  canceled: "closed",
  new: "lead",
  pending: "scheduled",
  current: "active",
  delinquent: "late",
  "past due": "late",
  overdue: "late",
};

const MACHINE_STATUS_MAP: Record<string, string> = {
  available: "available",
  assigned: "assigned",
  maintenance: "maintenance",
  retired: "retired",
  "in use": "assigned",
  "in-use": "assigned",
  active: "assigned",
  broken: "maintenance",
  repair: "maintenance",
  decommissioned: "retired",
  "out of service": "retired",
};

const MACHINE_TYPE_MAP: Record<string, string> = {
  washer: "washer",
  dryer: "dryer",
  set: "set",
  w: "washer",
  d: "dryer",
  "washing machine": "washer",
  wash: "washer",
  dry: "dryer",
  "washer/dryer": "set",
  "washer dryer": "set",
  combo: "set",
};

const PRONG_MAP: Record<string, string> = {
  "3-prong": "3-prong",
  "4-prong": "4-prong",
  "3 prong": "3-prong",
  "4 prong": "4-prong",
  "3": "3-prong",
  "4": "4-prong",
};

export const RENTER_FIELDS: ImportField[] = [
  {
    key: "name",
    label: "Name",
    placeholder: "",
    synonyms: ["full name", "renter name", "customer name", "renter full name", "tenant name", "customer", "client", "client name"],
    group: "renter",
    reviewWhenBlank: true,
  },
  {
    key: "phone",
    label: "Phone",
    placeholder: "",
    synonyms: ["phone number", "mobile", "cell", "cell phone", "telephone", "tel", "ph", "contact"],
    group: "renter",
  },
  {
    key: "email",
    label: "Email",
    placeholder: "",
    synonyms: ["email address", "e-mail", "email addr"],
    group: "renter",
  },
  {
    key: "laundrylord_email",
    label: "LaundryLord Email",
    placeholder: "",
    synonyms: ["owner email", "operator email", "account email", "laundrylord email"],
    group: "renter",
  },
  {
    key: "address",
    label: "Address",
    placeholder: "",
    synonyms: ["service address", "home address", "street address", "location", "addr", "delivery address", "install address"],
    group: "renter",
  },
  {
    key: "dryer_outlet",
    label: "Dryer Outlet",
    placeholder: "",
    synonyms: ["outlet", "outlet type", "dryer prong", "prong type"],
    group: "renter",
  },
  {
    key: "secondary_contact",
    label: "Secondary Contact",
    placeholder: "",
    synonyms: ["alt contact", "alternate contact", "second contact", "emergency contact"],
    group: "renter",
  },
  {
    key: "language",
    label: "Language",
    placeholder: "",
    synonyms: ["preferred language", "lang"],
    group: "renter",
  },
  {
    key: "status",
    label: "Status",
    placeholder: "",
    synonyms: ["renter status", "customer status", "account status"],
    group: "renter",
    valueType: "enum",
    enumMap: RENTER_STATUS_MAP,
  },
  {
    key: "lease_start_date",
    label: "Lease Start Date",
    placeholder: "",
    synonyms: ["start date", "lease begins", "lease date", "move in date", "install date"],
    group: "renter",
    valueType: "date",
  },
  {
    key: "monthly_rate",
    label: "Monthly Rate",
    placeholder: "",
    synonyms: ["monthly rent", "rent", "rate", "monthly rate $", "monthly fee", "monthly", "mo rate", "rent/mo", "rent mo"],
    group: "renter",
    valueType: "number",
  },
  {
    key: "late_fee",
    label: "Late Fee",
    placeholder: "",
    synonyms: ["late fee $", "late charge", "penalty"],
    group: "renter",
    valueType: "number",
  },
  {
    key: "install_fee",
    label: "Install Fee",
    placeholder: "",
    synonyms: ["install fee $", "installation fee", "setup fee"],
    group: "renter",
    valueType: "number",
  },
  {
    key: "deposit_amount",
    label: "Deposit",
    placeholder: "",
    synonyms: ["deposit $", "security deposit", "deposit amount"],
    group: "renter",
    valueType: "number",
  },
  {
    key: "install_fee_collected",
    label: "Install Fee Collected",
    placeholder: "",
    synonyms: ["install fee paid", "install collected"],
    group: "renter",
    valueType: "boolean",
  },
  {
    key: "deposit_collected",
    label: "Deposit Collected",
    placeholder: "",
    synonyms: ["deposit paid", "deposit received"],
    group: "renter",
    valueType: "boolean",
  },
  {
    key: "install_notes",
    label: "Install Notes",
    placeholder: "",
    synonyms: ["installation notes", "install info"],
    group: "renter",
  },
  {
    key: "notes",
    label: "Notes",
    placeholder: "",
    synonyms: ["renter notes", "customer notes", "comments"],
    group: "renter",
  },
  {
    key: "has_payment_method",
    label: "Card Set Up but no Autopay",
    placeholder: "",
    synonyms: [
      "card on file no autopay",
      "card added no autopay",
      "card set up no autopay",
      "payment method",
      "card on file",
    ],
    group: "renter",
    valueType: "boolean",
  },
];

export const MACHINE_FIELDS: ImportField[] = [
  {
    key: "type",
    label: "Type",
    placeholder: "",
    synonyms: ["machine type", "appliance type", "washer or dryer", "equipment type", "make", "appliance", "w/d", "washer dryer"],
    group: "machine",
    valueType: "enum",
    enumMap: MACHINE_TYPE_MAP,
    reviewWhenBlank: true,
  },
  {
    key: "model",
    label: "Model",
    placeholder: "",
    synonyms: ["model number", "model name", "model #", "model no", "model num"],
    group: "machine",
    reviewWhenBlank: true,
  },
  {
    key: "serial",
    label: "Serial #",
    placeholder: "",
    synonyms: ["serial number", "serial #", "sn", "serial no", "serial num", "s/n", "ser", "serial#"],
    group: "machine",
    reviewWhenBlank: true,
  },
  {
    key: "prong",
    label: "Prong",
    placeholder: "",
    synonyms: ["prong type", "cord type", "plug type"],
    group: "machine",
    valueType: "enum",
    enumMap: PRONG_MAP,
  },
  {
    key: "condition",
    label: "Condition",
    placeholder: "",
    synonyms: ["machine condition", "state", "cond"],
    group: "machine",
  },
  {
    key: "status",
    label: "Status",
    placeholder: "",
    synonyms: ["machine status", "availability", "avail", "in use"],
    group: "machine",
    valueType: "enum",
    enumMap: MACHINE_STATUS_MAP,
  },
  {
    key: "cost_basis",
    label: "Cost Basis ($)",
    placeholder: "",
    synonyms: ["cost", "cost basis $", "purchase price", "price", "acquisition cost"],
    group: "machine",
    valueType: "number",
  },
  {
    key: "sourced_from",
    label: "Sourced From",
    placeholder: "",
    synonyms: ["source", "acquired from", "vendor", "supplier", "purchased from"],
    group: "machine",
  },
  {
    key: "laundrylord_email",
    label: "LaundryLord Email",
    placeholder: "",
    synonyms: ["owner email", "operator email", "account email", "laundrylord email"],
    group: "machine",
  },
  {
    key: "notes",
    label: "Notes",
    placeholder: "",
    synonyms: ["machine notes", "comments"],
    group: "machine",
  },
];
